### ISSUE TITLE
opml 导入无法完全识别

### ISSUE THREAD

**Issue by iSteveyang** [indes/flowerss-bot#111]
![image](https://user-images.githubusercontent.com/20753221/121689814-aa6dfd80-caf7-11eb-8b82-bcfa4a1bf25d.png)
opml 导入无法识别
总是差几个

`<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
<head>
<title>Inoreader</title>
</head>
<body>
<outline text="Android" title="Android">
<outline xmlUrl="http://free.apprcn.com/category/android/feed/" title="反斗限免 » Android" type="rss" text="反斗限免 » Android" htmlUrl="http://free.apprcn.com/" />
</outline>
<outline text="Game" title="Game">
<outline type="rss" xmlUrl="http://free.apprcn.com/category/game/feed/" title="反斗限免 » 游戏" htmlUrl="http://free.apprcn.com/" text="反斗限免 » 游戏" />
</outline>
<outline text="iOS" title="iOS">
<outline title="反斗限免 » iOS" type="rss" htmlUrl="http://free.apprcn.com/" text="反斗限免 » iOS" xmlUrl="http://free.apprcn.com/category/ios/feed/" />
</outline>
<outline title="Mac" text="Mac">
<outline xmlUrl="http://free.apprcn.com/category/mac/feed/" text="反斗限免 » Mac" title="反斗限免 » Mac" type="rss" htmlUrl="http://free.apprcn.com/" />
</outline>
</body>
</opml>`

**Comment by iSteveyang** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/20753221/121690335-4c8de580-caf8-11eb-86ca-f64dc59ad57a.png">

**Comment by indes** [comment]
这种情况可以手动导入试试，一般是源订阅错误
