### ISSUE TITLE
tele的api还需要认证吗？没设置过啊

### ISSUE THREAD

**Issue by iSteveyang** [indes/flowerss-bot#118]
之前还是好好的，忽然出现
`{"level":"fatal","ts":"2021-07-10T17:48:53Z","caller":"bot/bot.go:53","msg":"telebot: Post https://api.telegram.org/bot /getMe: x509: certificate is valid for *.secure.latest.facebook.com, secure.latest.facebook.com, not api.telegram.org","stacktrace":"github.com/indes/flowerss-bot/bot.init.0\n\t/flowerss/bot/bot.go:53\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5228\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5223\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:190"}`

**Comment by boypt** [comment]
墙内机器？看着是被劫持了https

**Comment by iSteveyang** [comment]
洛杉矶的，现在还是这个问题，我该怎么操作？

**Comment by boypt** [comment]
你机器上跑一下`curl -v https://api.telegram.org/bot/getMe`试试？正常的话应该是下面那样的，你日志里面是api.telegram.org被劫持到了一个宣称是facebook服务器的地址，检查一下你的DNS配置之类的。

```
curl -v https://api.telegram.org/bot/getMe
*   Trying 149.154.167.220:443...
* TCP_NODELAY set
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; CN=api.telegram.org
*  start date: Mar 24 13:48:17 2020 GMT
*  expire date: May 23 16:17:38 2022 GMT
*  subjectAltName: host "api.telegram.org" matched cert's "api.telegram.org"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a502bfcd40)
> GET /bot/getMe HTTP/2
> Host: api.telegram.org
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404 
< server: nginx/1.18.0
< date: Fri, 16 Jul 2021 04:15:11 GMT
< content-type: application/json
< content-length: 55
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< access-control-allow-origin: *
< access-control-expose-headers: Content-Length,Content-Type,Date,Server,Connection
< 
* Connection #0 to host api.telegram.org left intact
```

**Comment by iSteveyang** [comment]
* Expire in 0 ms for 6 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 2 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 2 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 2 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 2 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 2 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 0 ms for 1 (transfer 0x55905afd1c10)
* Expire in 2 ms for 1 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
* Expire in 4 ms for 1 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
* Expire in 1 ms for 1 (transfer 0x55905afd1c10)
*   Trying 149.154.167.220...
* TCP_NODELAY set
* Expire in 149997 ms for 3 (transfer 0x55905afd1c10)
* Expire in 200 ms for 4 (transfer 0x55905afd1c10)
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; CN=api.telegram.org
*  start date: Mar 24 13:48:17 2020 GMT
*  expire date: May 23 16:17:38 2022 GMT
*  subjectAltName: host "api.telegram.org" matched cert's "api.telegram.org"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55905afd1c10)
> GET /bot/getMe HTTP/2
> Host: api.telegram.org
> User-Agent: curl/7.64.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404
< server: nginx/1.18.0
< date: Fri, 16 Jul 2021 06:10:49 GMT
< content-type: application/json
< content-length: 55
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< access-control-allow-origin: *
< access-control-expose-headers: Content-Length,Content-Type,Date,Server,Connection
<
* Connection #0 to host api.telegram.org left intact
{"ok":false,"error_code":404,"description":"Not Found"}#

**Comment by boypt** [comment]
有这么一行`*  subjectAltName: host "api.telegram.org" matched cert's "api.telegram.org"`说明https是正确链接到tg服务器的。

但是bot那日志是实际上连到了facebook服务器，怀疑是dns出问题

**Comment by iSteveyang** [comment]
好的，谢谢，是119.29.29.29的问题，换了1.1.1.1就好了，DNS污染？
