### ISSUE TITLE
【Bug 反馈】 flowerss-bot 一夜之间占满了我所有的 Linux 空间

### ISSUE THREAD

**Issue by TigerCubDen** [indes/flowerss-bot#119]
一觉醒来，发现我的服务器上剩余的十多G空间全部占满。经排查，可以看到 flowerss 容器的占用大小非常惊人，猜测是程序出错疯狂输出日志所致。于是去查了下日志文件。
![Snipaste_2021-07-15_10-15-50](https://user-images.githubusercontent.com/55782476/125717735-0b196a95-0f3c-4bf6-b173-1de9c85ed058.png)

日志文件占了整整12G。
![Snipaste_2021-07-15_10-25-17](https://user-images.githubusercontent.com/55782476/125718486-4d59b2a8-0999-4ff0-af59-4affe2ef3c41.png)

查看日志内容，也可以发现输出的全是乱七八糟的出错信息。
![Snipaste_2021-07-15_10-30-52](https://user-images.githubusercontent.com/55782476/125718826-05b7747b-6004-4226-9452-f3c82ef9fe29.png)

不知道作者有没有什么好的解决方案，比如完善下日志输出，只给出简短的错误总结。避免下次出错时又发生同样的事情。
希望开发者能够尽快解决这个问题，谢谢啦~

**Comment by boypt** [comment]
这不都很明确的日志了嘛，你配置了127.0.0.1:1080的代理，但是bot连不上

**Comment by TigerCubDen** [comment]
> 这不都很明确的日志了嘛，你配置了127.0.0.1:1080的代理，但是bot连不上

我同时运行的另一个 rssbot 当时却可以连上。但这不是重点，我的意思是不要疯狂输出日志（一秒几十条以上），迅速把空间占满。

**Comment by indes** [comment]
这个是telebot框架报的错，flowerss-bot无法控制，也不应该限制。
