### ISSUE TITLE
xml全文订阅报错 求修复

### ISSUE THREAD

**Issue by dylanbai8** [indes/flowerss-bot#12]
https://feedx.net/rss/zhihudaily.xml

https://feedx.net/rss/scmp.xml

![56.png](https://i.loli.net/2019/09/26/d1yYNVTifLhUMpP.png)

**Comment by indes** [comment]
目前已经能成功订阅这两个rss。

**Comment by ottokang** [comment]
目前知乎日報的 RSS 又壞了，9月後就沒有更新
