### ISSUE TITLE
希望开发者提供一个“去重开关”

### ISSUE THREAD

**Issue by Kawaii-KM** [indes/flowerss-bot#122]
[Steam周榜](https://store.steampowered.com/feeds/weeklytopsellers.xml) 有时会重复排名，比如7.25的推送
![image](https://user-images.githubusercontent.com/56059155/126907474-d6b99f30-b8d8-4570-901d-fd62d1cdf21d.png)

**Comment by indes** [comment]
![image](https://user-images.githubusercontent.com/4705478/127018683-d20d150f-fbf5-4a34-a839-baeee12b7ebb.png)

flowerss已有去重逻辑，但是rss源本身有重复内容，这种情况阅读器应该忠于源内容，不应该增减源内容。
