### ISSUE TITLE
希望可以支持各源单独设置轮询时间

### ISSUE THREAD

**Issue by ccinoo** [indes/flowerss-bot#20]
希望可以支持各源单独设置轮询时间。因为：
1、有的源反扒要求比较严格。
2、有的源每天更新频率不高，而有的更新频率又高，只能统一设置一个更新频率不合适。

**Comment by Arepeater** [comment]
顺带这个开着，可以再进一步提一下吗?希望增加定时扫描的设置，因为隔断着推送消息实在有点打扰专注的工作，我总是控制不住自己要去看一眼。
