### ISSUE TITLE
*

### ISSUE THREAD

**Issue by EdisonJwa** [indes/flowerss-bot#21]
*

**Comment by indes** [comment]
该atom格式有问题，解析器无法正常解析
![image](https://user-images.githubusercontent.com/4705478/70200802-9baec980-174f-11ea-8c64-859224b8b0eb.png)
![image](https://user-images.githubusercontent.com/4705478/70200827-aff2c680-174f-11ea-8aec-fadb90bd9db3.png)
http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.wevg.org%2Fatom.xml

**Comment by EdisonJwa** [comment]
> 该atom格式有问题，解析器无法正常解析
> ![image](https://user-images.githubusercontent.com/4705478/70200802-9baec980-174f-11ea-8c64-859224b8b0eb.png)
> ![image](https://user-images.githubusercontent.com/4705478/70200827-aff2c680-174f-11ea-8aec-fadb90bd9db3.png)
> http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.wevg.org%2Fatom.xml

似乎是hexo 生成的时候 又渲染了一遍

**Comment by EdisonJwa** [comment]
抓取失败的原因 翻阅cloudflare 防火墙记录发现是因为 rssbot 的useragent 导致返回chaptcha

**Comment by EdisonJwa** [comment]
> 该atom格式有问题，解析器无法正常解析
> ![image](https://user-images.githubusercontent.com/4705478/70200802-9baec980-174f-11ea-8c64-859224b8b0eb.png)
> ![image](https://user-images.githubusercontent.com/4705478/70200827-aff2c680-174f-11ea-8aec-fadb90bd9db3.png)
> http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.wevg.org%2Fatom.xml

This par problem was fixed after I upgraded the atom generator plugin package
