### ISSUE TITLE
关于即时预览按钮

### ISSUE THREAD

**Issue by Abettoe** [indes/flowerss-bot#3]
![Screenshot_20190522230416](https://user-images.githubusercontent.com/26241099/58185592-f61d9680-7ce5-11e9-94ad-350adf2973ee.jpg)
为什么推送都没有即时预览的按钮呢？
把链接复制转发出去又有了
![Screenshot_20190522230622](https://user-images.githubusercontent.com/26241099/58185754-3da42280-7ce6-11e9-85b8-14a6ca0286bb.jpg)

**Comment by indes** [comment]
能否告知订阅源链接？

**Comment by Abettoe** [comment]
这个没有按钮https://rsshub.app/nytimes/dual 
这个有https://rsshub.app/bbc/chinese

**Comment by indes** [comment]
已经调整消息中的链接顺序，有所改善，但是依旧会出现少部分情况无法出现即时预览按钮的情况，暂时不清楚Telegram客户端如何判定是否显示即时预览按钮。
