### ISSUE TITLE
docker成功部署，没有推送

### ISSUE THREAD

**Issue by zxjack** [indes/flowerss-bot#35]
docker部署成功，运行起来，订阅也是ok的，但是没有推送，是啥情况？

**Comment by indes** [comment]
麻烦附上docker日志

**Comment by Sheldonsix** [comment]
`2020-04-02T12:37:49.206685291Z 2020/04/02 12:37:49 API error from https://api.telegra.ph/createPage: FLOOD_WAIT_4
2020-04-02T12:37:49.206952992Z 2020/04/02 12:37:49 Create telegraph page error: FLOOD_WAIT_4
2020-04-02T12:37:49.675698680Z 2020/04/02 12:37:49 API error from https://api.telegra.ph/createPage: FLOOD_WAIT_4
2020-04-02T12:37:49.676213610Z 2020/04/02 12:37:49 Create telegraph page error: FLOOD_WAIT_4
`
请问是自己申请 telegraph 的 api 有问题吗？

**Comment by indes** [comment]
> `2020-04-02T12:37:49.206685291Z 2020/04/02 12:37:49 API error from https://api.telegra.ph/createPage: FLOOD_WAIT_4 2020-04-02T12:37:49.206952992Z 2020/04/02 12:37:49 Create telegraph page error: FLOOD_WAIT_4 2020-04-02T12:37:49.675698680Z 2020/04/02 12:37:49 API error from https://api.telegra.ph/createPage: FLOOD_WAIT_4 2020-04-02T12:37:49.676213610Z 2020/04/02 12:37:49 Create telegraph page error: FLOOD_WAIT_4 `
> 请问是自己申请 telegraph 的 api 有问题吗？

不是，这是telegraph api请求数过多，配置多个telegraph api可以解决该问题。

**Comment by Sheldonsix** [comment]
> > `2020-04-02T12:37:49.206685291Z 2020/04/02 12:37:49 API error from https://api.telegra.ph/createPage: FLOOD_WAIT_4 2020-04-02T12:37:49.206952992Z 2020/04/02 12:37:49 Create telegraph page error: FLOOD_WAIT_4 2020-04-02T12:37:49.675698680Z 2020/04/02 12:37:49 API error from https://api.telegra.ph/createPage: FLOOD_WAIT_4 2020-04-02T12:37:49.676213610Z 2020/04/02 12:37:49 Create telegraph page error: FLOOD_WAIT_4 `
> > 请问是自己申请 telegraph 的 api 有问题吗？
> 
> 不是，这是telegraph api请求数过多，配置多个telegraph api可以解决该问题。

好的 谢谢你，更换了 api 就好了
