### ISSUE TITLE
怎么查看频道的订阅？

### ISSUE THREAD

**Issue by chengzhycn** [indes/flowerss-bot#37]
直接 /sub xxxxx 通过 /list 能看到订阅列表，/sub @xxx xxxxx 再 /list 看不到订阅列表

**Comment by 443344** [comment]
> 直接 /sub xxxxx 通过 /list 能看到订阅列表，/sub @xxx xxxxx 再 /list 看不到订阅列表

/sub @ChannelID [url] 订阅
/unsub @ChannelID [url] 取消订阅
/list @ChannelID 查看当前订阅
/unsuball @ChannelID 取消所有订阅
