### ISSUE TITLE
SCMP的即时预览有问题

### ISSUE THREAD

**Issue by TommyHui1984** [indes/flowerss-bot#39]
南华早报的即时预览只有一部分，不是全文，希望休整一下啊

**Comment by indes** [comment]
这个极有可能是rss源输出的问题，bot不会截短rss内容，请确认rss是否为全文输出。

**Comment by TommyHui1984** [comment]
相同链接在instantVIew Bot 可以使用

**Comment by indes** [comment]
> 相同链接在instantVIew Bot 可以使用

麻烦附上rss源链接。

**Comment by TommyHui1984** [comment]
https://www.scmp.com/rss/4/feed

**Comment by TommyHui1984** [comment]
> > 相同链接在instantVIew Bot 可以使用
> 
> 麻烦附上rss源链接。

https://www.scmp.com/rss/4/feed

**Comment by indes** [comment]
![image](https://user-images.githubusercontent.com/4705478/81397965-ec8d7880-915a-11ea-8050-ed0816ae16bc.png)
该rss源并非全文输出，请更换全文输出的rss源，例如：[https://feedx.net/rss/scmp.xml](https://feedx.net/rss/scmp.xml)
