### ISSUE TITLE
同是instagram的源，一个支持，另一个却不支持…

### ISSUE THREAD

**Issue by GH74138** [indes/flowerss-bot#4]
https://rsshub.app/instagram/user/magnumphotos （支持）https://rsshub.app/instagram/user/chenyanzi98（不支持）

**Comment by indes** [comment]
是订阅失败还是更新失败？

**Comment by GH74138** [comment]
订阅失败

**Comment by indes** [comment]
在浏览器中打开你发送的订阅链接发现无法正确返回xml文件。
![image](https://user-images.githubusercontent.com/4705478/58326582-d4e0b580-7e5f-11e9-988e-2c1e9643a1d3.png)
这种情况是rsshub的问题，rsshub官方的实例由于使用人数较多，经常出现429错误，**建议自建rsshub或者使用其他订阅源**。可以尝试使用浏览器打开订阅链接，如果不能正确加载xml则说明是rss服务器的问题。
