### ISSUE TITLE
logs里面总是出现api error: Too Many Requests: retry after 

### ISSUE THREAD

**Issue by RezaFeng** [indes/flowerss-bot#41]
配置里面设置扫描间隔是30分钟，错误尝试次数是30，配合自搭建的rsshub使用

**Comment by indes** [comment]
能否附上完整日志截图

**Comment by RezaFeng** [comment]
> 能否附上完整日志截图

2020/04/19 08:06:22 DB Path: ./data.db
2020/04/19 08:06:22 Telegraph Enabled, Token len:  8 Token:  [5d4e2021151ee7104baa32c1622d899ea14be426a0f0da1133102c5af62b dcd1a5daf7c2def1a9760b5d4aa151fda1a9381f3cd8820f18e09de1eb13 ef477760f479a24caacd77eba895092dc2aa83638a3ac7b78e56aff7b769 a5fde955bb90ce45e5241bd7325a939507e56a0fb6a0374145eb2518f9b6 692781e520b8a50e7e0c708906736940407e4264e894ad2d066a005d30be 246ebe0f01e4e7fc5f503188b8068a191e5f1e25e92a832b010561a42887 75b7fa206d50f0c233e426ad06279c481533aa32cc94f763df92852d1677 393f85bd67a6dcef39120ab32d2d542389395c1ed2bf5b9bbfbb77d82b61]
2020/04/19 08:06:33 request error: Post https://api.telegra.ph/getAccountInfo: dial tcp 174.37.175.229:443: i/o timeout
2020/04/19 08:06:33 Telegraph load error: Post https://api.telegra.ph/getAccountInfo: dial tcp 174.37.175.229:443: i/o timeout token: dcd1a5daf7c2def1a9760b5d4aa151fda1a9381f3cd8820f18e09de1eb13
2020/04/19 08:06:45 request error: Post https://api.telegra.ph/getAccountInfo: dial tcp 69.171.234.18:443: i/o timeout
2020/04/19 08:06:45 Telegraph load error: Post https://api.telegra.ph/getAccountInfo: dial tcp 69.171.234.18:443: i/o timeout token: 692781e520b8a50e7e0c708906736940407e4264e894ad2d066a005d30be
2020/04/19 08:06:47 request error: Post https://api.telegra.ph/getAccountInfo: dial tcp 31.13.66.6:443: connect: network is unreachable
2020/04/19 08:06:47 Telegraph load error: Post https://api.telegra.ph/getAccountInfo: dial tcp 31.13.66.6:443: connect: network is unreachable token: 393f85bd67a6dcef39120ab32d2d542389395c1ed2bf5b9bbfbb77d82b61
2020/04/19 08:06:47 Bot Token: 1219638341:AAH0WpMaEGjPCH0ly6saX57Q26cTcyvtPxc Endpoint: https://api.telegram.org
2020/04/19 08:06:57 Unable to make request:  EOF   https://www.rezafeng.top:1201/cnbeta
2020/04/19 08:06:58 Created telegraph page url: https://telegra.ph/使命召唤战区外挂猖獗主机玩家无奈关闭跨平台匹配---IT之家-04-19-6
2020/04/19 08:07:00 Created telegraph page url: https://telegra.ph/百度网盘推出用户奖励计划分享闲置上行宽带最高占-1MBs---IT之家-04-19-6
2020/04/19 08:07:01 Source Title: <IT之家> Subscriber: 1 New Contents: 2
2020/04/19 08:09:10 Unable to make request:  EOF   https://www.rezafeng.top:1201/instagram/user/tarankaaa
2020/04/19 08:09:26 request error: Post https://api.telegra.ph/createPage: dial tcp 67.228.102.32:443: i/o timeout
2020/04/19 08:09:26 Create telegraph page error: Post https://api.telegra.ph/createPage: dial tcp 67.228.102.32:443: i/o timeout
2020/04/19 08:09:26 Source Title: <脆膝哥的微博> Subscriber: 1 New Contents: 1
2020/04/19 08:11:27 Unable to make request:  EOF   https://www.rezafeng.top:1201/instagram/user/juno_mak
2020/04/19 08:11:28 Unable to make request:  expected element type <feed> but have <html>   https://www.rezafeng.top:1201/instagram/user/kalok_
2020/04/19 08:11:30 Unable to make request:  expected element type <feed> but have <html>   https://www.rezafeng.top:1201/instagram/user/kaytse
2020/04/19 08:11:36 Created telegraph page url: https://telegra.ph/讲真黑人穿什么衣服都潮果然人身上的自然与野性是最好的外表---每天赚一咪的微博-04-19
2020/04/19 08:11:36 Source Title: <每天赚一咪的微博> Subscriber: 1 New Contents: 1
2020/04/19 08:11:40 Unable to make request:  expected element type <feed> but have <html>   https://www.rezafeng.top:1201/instagram/user/lalalalisa_m
2020/04/19 08:11:42 Source Title: <普罗的绿灯的微博> Subscriber: 1 New Contents: 0
2020/04/19 08:11:44 Unable to make request:  expected element type <feed> but have <html>   https://www.rezafeng.top:1201/instagram/user/fishleong616
2020/04/19 08:13:45 Unable to make request:  expected element type <feed> but have <html>   https://www.rezafeng.top:1201/instagram/user/stefsunyanzi
2020/04/19 08:13:47 Source Title: <kasumi arimura 有村架純&staff(@kasumi_arimura.official)'s Instagram> Subscriber: 1 New Contents: 0
2020/04/19 08:13:49 Unable to make request:  expected element type <feed> but have <html>   https://www.rezafeng.top:1201/instagram/user/aragakiyui_fanspage
2020/04/19 08:13:49 Unable to make request:  expected element type <feed> but have <html>   https://www.rezafeng.top:1201/t66y/16
2020/04/19 08:13:50 Source Title: <博物杂志的微博> Subscriber: 1 New Contents: 0
2020/04/19 08:13:50 Source Title: <博物杂志的微博> Subscriber: 1 New Contents: 0
2020/04/19 08:13:52 Source Title: <Trending  repositories on GitHub today · GitHub> Subscriber: 1 New Contents: 0
2020/04/19 08:14:05 Source Title: <广东工业大学校内新闻网> Subscriber: 1 New Contents: 0
2020/04/19 08:24:45 telebot: could not fetch new updates
gopkg.in/tucnak/telebot%2ev2.init
	/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.0.0-20191005061224-d0707a9d73c4/poller.go:10
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5222
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5217
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5217
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5217
runtime.main
	/usr/local/go/src/runtime/proc.go:190
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
	/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.0.0-20191005061224-d0707a9d73c4/util.go:12
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
	/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.0.0-20191005061224-d0707a9d73c4/poller.go:97
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by RezaFeng** [comment]
> 能否附上完整日志截图

2020/04/19 03:21:23 Create telegraph page error: Post https://api.telegra.ph/createPage: x509: certificate is valid for *.dns.fbinfra.net, *.edgeos.fbinfra.net, *.offnet.fbinfra.net, *.fna.fbinfra.net, fbinfra.net, *.fnedge.fbinfra.net, *.ntp.fbinfra.net, *.yum.fbinfra.net, *.sr-offnet.fbinfra.net, *.tw.fbinfra.net, *.any.fbinfra.net, *.fbinfra.net, not api.telegra.ph
2020/04/19 03:21:24 Created telegraph page url: https://telegra.ph/NVIDIA发布RTX-Voice-一个AI驱动的音频降噪软件---cnBeta-04-19-5
2020/04/19 03:21:25 Created telegraph page url: https://telegra.ph/纳米技术或可灭活新冠病毒-不破坏人体其他功能---cnBeta-04-19-5
2020/04/19 03:21:26 request error: Post https://api.telegra.ph/createPage: x509: certificate is valid for redirweb2.reg.free.org, not api.telegra.ph
2020/04/19 03:21:26 Create telegraph page error: Post https://api.telegra.ph/createPage: x509: certificate is valid for redirweb2.reg.free.org, not api.telegra.ph
2020/04/19 03:21:28 Created telegraph page url: https://telegra.ph/青桔单车获超10亿美元融资-竞争格局已重构---cnBeta-04-19-5
2020/04/19 03:21:29 Created telegraph page url: https://telegra.ph/首发骁龙865三星Note-20参数曝光电池增至4000mAh---cnBeta-04-19-5
2020/04/19 03:21:39 request error: Post https://api.telegra.ph/createPage: dial tcp 67.15.100.252:443: i/o timeout
2020/04/19 03:21:39 Create telegraph page error: Post https://api.telegra.ph/createPage: dial tcp 67.15.100.252:443: i/o timeout
2020/04/19 03:21:40 Created telegraph page url: https://telegra.ph/小米开源-Redmi-Note-8-Pro-和-Note-9-Pro-系列的内核源码---cnBeta-04-19-5
2020/04/19 03:21:41 Created telegraph page url: https://telegra.ph/视频iPad-Pro妙控键盘开箱上手-和Smart-Keyboard有啥区别---cnBeta-04-19-5
2020/04/19 03:21:51 request error: Post https://api.telegra.ph/createPage: dial tcp 69.171.245.49:443: i/o timeout
2020/04/19 03:21:51 Create telegraph page error: Post https://api.telegra.ph/createPage: dial tcp 69.171.245.49:443: i/o timeout
2020/04/19 03:21:51 Source Title: <cnBeta> Subscriber: 1 New Contents: 43
2020/04/19 03:22:11 api error: Too Many Requests: retry after 40
2020/04/19 03:22:11 api error: Too Many Requests: retry after 40
2020/04/19 03:22:12 api error: Too Many Requests: retry after 39
2020/04/19 03:22:12 api error: Too Many Requests: retry after 39
2020/04/19 03:22:13 api error: Too Many Requests: retry after 38
2020/04/19 03:22:13 api error: Too Many Requests: retry after 38
2020/04/19 03:22:14 api error: Too Many Requests: retry after 38
2020/04/19 03:22:14 api error: Too Many Requests: retry after 37
2020/04/19 03:22:15 api error: Too Many Requests: retry after 37
2020/04/19 03:22:15 api error: Too Many Requests: retry after 36
2020/04/19 03:22:15 api error: Too Many Requests: retry after 36
2020/04/19 03:22:16 api error: Too Many Requests: retry after 35
2020/04/19 03:22:16 api error: Too Many Requests: retry after 35
2020/04/19 03:22:17 api error: Too Many Requests: retry after 34
2020/04/19 03:22:17 api error: Too Many Requests: retry after 34
2020/04/19 03:22:18 api error: Too Many Requests: retry after 34
2020/04/19 03:22:18 api error: Too Many Requests: retry after 33
2020/04/19 03:22:18 api error: Too Many Requests: retry after 33
2020/04/19 03:22:19 api error: Too Many Requests: retry after 32
2020/04/19 03:22:19 api error: Too Many Requests: retry after 32
2020/04/19 03:22:20 api error: Too Many Requests: retry after 31
2020/04/19 03:22:20 api error: Too Many Requests: retry after 31
2020/04/19 03:22:21 api error: Too Many Requests: retry after 30
2020/04/19 03:22:31 request error: Post https://api.telegra.ph/createPage: dial tcp 67.228.221.221:443: i/o timeout
2020/04/19 03:22:31 Create telegraph page error: Post https://api.telegra.ph/createPage: dial tcp 67.228.221.221:443: i/o timeout

**Comment by indes** [comment]
> Create telegraph page error: Post https://api.telegra.ph/createPage: dial tcp 67.228.221.221:443: i/o timeout

用户这边的表现是无法收到该文章推送还是该文章推送没有telegraph链接？

**Comment by RezaFeng** [comment]
> > Create telegraph page error: Post https://api.telegra.ph/createPage: dial tcp 67.228.221.221:443: i/o timeout
> 
> 用户这边的表现是无法收到该文章推送还是该文章推送没有telegraph链接？

我不确定是否漏了信息的推送，但是有时候有些推送是没有telegraph链接的

**Comment by indes** [comment]
日志中`request error: Post api.telegra.ph/createPage: dial tcp 67.15.100.252:443: i/o timeout`错误比较多，建议检查一下网络情况。
`api error: Too Many Requests`应该是新的文章数太多，推送时大量调用telegraph api，触发到tg服务器的限制规则了，可能需要等后面的代码更新才能解决该问题。

**Comment by RezaFeng** [comment]
> 日志中`request error: Post api.telegra.ph/createPage: dial tcp 67.15.100.252:443: i/o timeout`错误比较多，建议检查一下网络情况。
> `api error: Too Many Requests`应该是新的文章数太多，推送时大量调用telegraph api，触发到tg服务器的限制规则了，可能需要等后面的代码更新才能解决该问题。

创建telegraph的频率太快了可能，部分网站的抓取似乎容易被反爬，像instagram就会经常request EOF

**Comment by indes** [comment]
> > 日志中`request error: Post api.telegra.ph/createPage: dial tcp 67.15.100.252:443: i/o timeout`错误比较多，建议检查一下网络情况。
> > `api error: Too Many Requests`应该是新的文章数太多，推送时大量调用telegraph api，触发到tg服务器的限制规则了，可能需要等后面的代码更新才能解决该问题。
> 
> 创建telegraph的频率太快了可能，部分网站的抓取似乎容易被反爬，像instagram就会经常request EOF

是的，后期会尝试改进抓取策略。
