### ISSUE TITLE
错误Unable to make request:  expected element type <feed> but have <html>

### ISSUE THREAD

**Issue by RezaFeng** [indes/flowerss-bot#42]
关注的instagram有部分会出现该错误
`2020/04/20 04:28:04 Source Title: <kasumi arimura 有村架純&staff(@kasumi_arimura.official)'s Instagram> Subscriber: 1 New Contents: 0`
`2020/04/20 04:28:06 Unable to make request:  expected element type <feed> but have <html>   https://www.xxxxx.top:1200/instagram/user/aragakiyui_fanspage`

**Comment by indes** [comment]
如果订阅只是有时会出现这样的错误，可能是订阅源的输出有问题，或是抓取频率过高被服务器拦截，可以尝试降低抓取频率。
