### ISSUE TITLE
Rss标题会自动去除大括号[ ]

### ISSUE THREAD

**Issue by Ukenn2112** [indes/flowerss-bot#43]
比如原标题:
**[全职猎人2011][HUNTERxHUNTER][HUNTERxHUNTER (2011) / Hunter x Hunter (2011)][BDRip] **

rss推送后就会变成:
**全职猎人2011  HUNTERxHUNTER  HUNTERxHUNTER (2011) / Hunter x Hunter (2011)  BDRip**

由于去除大括号就会影响阅读，看起来毕竟别扭（
请问，如何让这个框框不被去除掉？

**Comment by Ukenn2112** [comment]
> 比如原标题:
> [全职猎人2011][HUNTERxHUNTER][HUNTERxHUNTER (2011) / Hunter x Hunter (2011)][BDRip] 
> 
> rss推送后就会变成:
> **全职猎人2011  HUNTERxHUNTER  HUNTERxHUNTER (2011) / Hunter x Hunter (2011)  BDRip**
> 
> 由于去除大括号就会影响阅读，看起来毕竟别扭（
> 请问，如何让这个框框不被去除掉？

**Comment by indes** [comment]
已修复 19045266235e6bf7a0c3182c16ae08335a4e08df
