### ISSUE TITLE
/check指令似乎无法使用

### ISSUE THREAD

**Issue by CuteLouise** [indes/flowerss-bot#58]
![image](https://user-images.githubusercontent.com/43903287/89029431-05c05280-d361-11ea-87df-6a68f045b128.png)

麻烦大佬帮我看看，是我的使用方法不对吗

**Comment by prnake** [comment]
是通过编译部署的吗

**Comment by CuteLouise** [comment]
> 是通过编译部署的吗

是按照您的docker教程部署的

**Comment by prnake** [comment]
docker 和 release 都没更新，用[源码编译部署](https://flowerss-bot.now.sh/#/install?id=%e6%ba%90%e7%a0%81%e7%bc%96%e8%af%91%e9%83%a8%e7%bd%b2)

**Comment by CuteLouise** [comment]
已解决，感谢
