### ISSUE TITLE
消息模板不能生效

### ISSUE THREAD

**Issue by artxia** [indes/flowerss-bot#70]
![image](https://user-images.githubusercontent.com/50513568/95650882-1c311a00-0b19-11eb-91ed-0d732ee4f352.png)

配置文件写法如图，`>`和`｜`写法都尝试过，消息推送过来还是默认样式。
ps:手动修改默认样式的代码，可以修改消息模版

消息模版参考 https://github.com/indes/flowerss-bot/pull/25

**Comment by indes** [comment]
已修复
