### ISSUE TITLE
curl: (35) Peer reports incompatible or unsupported protocol version.

### ISSUE THREAD

**Issue by xljabbber** [indes/flowerss-bot#73]
如果要使用应用内部即时预览，必须在配置文件中填写telegraph_token配置项，电报令牌申请命令如下
curl https://api.telegra.ph/createAccount?short_name=flowerss&author_name=flowerss&author_url=https://github.com/indes/flowerss-bot
提示 curl: (35) Peer reports incompatible or unsupported protocol version.
 这个怎么解决谢谢

**Comment by indes** [comment]
请加上协议 curl https://api.telegra.ph/createAccount?short_name=flowerss&author_name=flowerss&author_url=https://github.com/indes/flowerss-bot
