### ISSUE TITLE
含有括号[]的标题超链接显示错误『最新版本』| Wrong Hyperlink format on title include bracket []『Latest Version』

### ISSUE THREAD

**Issue by ElvisXJ** [indes/flowerss-bot#77]
indes 你好

开issue之前搜索了，之前有issue提到 方括号[]错误问题，并且显示已修复。
但是在实际测试中发现格式仍然不正常，具体可见下图
![image](https://user-images.githubusercontent.com/38271881/100494069-eb647d00-3178-11eb-80e4-91aa7eb562ea.png)

**测试环境：**
Docker 部署 『latest 和 nightly均尝试了』

**配置文件：**
bot_token: xxxxx
telegraph_token:
telegraph_account:
telegraph_author_name:
telegraph_author_url: https://t.me/xjzim
socks5:
disable_web_page_preview: true
update_interval: 10
user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**问题表现：**
对于有 [] 的位置，bot显示为方括号前加一个 `\` 符号，之后在标题后 () 显示链接；导致并不能按照正常的[]()格式显示超链接

**Comment by indes** [comment]
能否附上出现[]错误的rss源链接？

**Comment by ElvisXJ** [comment]
> 能否附上出现[]错误的rss源链接？

https://www.lowendtalk.com/categories/offers/feeds.rss

**Comment by indes** [comment]
已修复 ced91b53dc6c1d80628a377615afdda26afca7a6
