### ISSUE TITLE
rss中文乱码

### ISSUE THREAD

**Issue by gpseaver** [indes/flowerss-bot#89]
订阅源的时候乱码

拉取的时候也乱码

rss源：
/sub https://www.52pojie.cn/forum.php?mod=rss&fid=16&auth=0

<img src = 'https://ftp.bmp.ovh/imgs/2021/02/44b930e458bba7a1.png' />

<img src = 'https://ftp.bmp.ovh/imgs/2021/02/dc514d4c0e198575.png' />

**Comment by indes** [comment]
暂时不支持gb2312编码，已经在todolist中了#71
