### ISSUE TITLE
建议：增加批量订阅和批量导出的功能

### ISSUE THREAD

**Issue by sakuramisaki** [indes/flowerss-bot#9]
之前已经跟您（开发者）谈过了，怕您给忘了就写在issues里了。
批量订阅示例:

> /sub url01  
> /sub url02  
> /sub url03
> 

每个订阅地址一行，这样就不用一行一行输入了，直接复制粘贴就能一次性订阅大量RSS了。
注:原版本是没有批量订阅的功能的，一次性输入多行订阅地址，默认是只能订阅第一行的。
还有的话，我在想既然有import，那为什么就没有export呢？我建议您增加导出功能呢！
虽然导出成文件实现起来可能有些困难，但是导出成文本消息实现起来就简单一些了。
导出的文字示例:
> /sub url01  
> /sub url02  
> /sub url03
> 
我在想:既然导出的目的是为了备份，备份的目的是为了再次导入，那么把导出的文字做成导入的格式不是简单明了吗？

**Comment by sakuramisaki** [comment]
NodeRSSBot同样也是telegram机器人，它可以把订阅源导出为opml文件，您可以借鉴一下。https://github.com/fengkx/NodeRSSBot

**Comment by indes** [comment]
已添加导出功能 780ca0015ffb772c2a7c004a393f9298c2d07fdd
