### ISSUE TITLE
使用一段时间后的功能建议

### ISSUE THREAD

**Issue by hellodword** [indes/flowerss-bot#90]
感谢 flowerss-bot

---

- `/setthis` 类似于 [`/unsubthis`](https://github.com/iovxw/rssbot/blob/a0c843b4e89988c9dce76c68857b1542fc3256e3/README.md#L21:6) 功能，可以根据 reply 对特定的 feed 进行操作，否则订阅的 feed 很多的时候 `/set` 不够好用。

接着对 `/set` 和 `/setthis` 功能的 toggle 进行扩展：

- 重命名，理由是有些 feed 的 title 很随意，例如 rsshub 的 [知乎话题](https://rsshub.app/zhihu/topic/19828946)。
- 附加信息，可以对某条消息对应的 feed 进行附加自定义消息，通常是一段文字，当订阅了很多更新周期相当长但又希望订阅的 feed 时会很有用。
- `/setinterval` 功能。

**Comment by faustliang** [comment]
> 感谢 flowerss-bot
> 
> 
> 
> ---
> 
> 
> 
> - `/setthis` 类似于 [`/unsubthis`](https://github.com/iovxw/rssbot/blob/a0c843b4e89988c9dce76c68857b1542fc3256e3/README.md#L21:6) 功能，可以根据 reply 对特定的 feed 进行操作，否则订阅的 feed 很多的时候 `/set` 不够好用。
> 
> 
> 
> 接着对 `/set` 和 `/setthis` 功能的 toggle 进行扩展：
> 
> 
> 
> - 重命名，理由是有些 feed 的 title 很随意，例如 rsshub 的 [知乎话题](https://rsshub.app/zhihu/topic/19828946)。
> 
> - 附加信息，可以对某条消息对应的 feed 进行附加自定义消息，通常是一段文字，当订阅了很多更新周期相当长但又希望订阅的 feed 时会很有用。
> 
> - `/setinterval` 功能。
> 
> 

可以使用吗？我发指令一直没回复
