### ISSUE TITLE
订阅地址不识别问号

### ISSUE THREAD

**Issue by changyexing** [indes/flowerss-bot#91]
![image](https://user-images.githubusercontent.com/47708150/110627922-7aa01880-81dd-11eb-89fe-0cc8338c1231.png)
如图，没算上最后那个问号导致订阅失败🤣

**Comment by faustliang** [comment]
请问你是怎么使用的呢？我用的这个bot一直没反应![image](https://user-images.githubusercontent.com/63723974/111039475-3b85f780-8469-11eb-8eb0-1e4b007d3d60.jpeg)

**Comment by changyexing** [comment]
你这个凉了，换其他的机器人用吧

**Comment by jinzaizhichi** [comment]
@faustliang 源码部署，数据库用mysql。

**Comment by faustliang** [comment]
> 你这个凉了，换其他的机器人用吧
啊，这是开源的嘛？只能自建？大佬可有好用的bot推荐一下，今年没时间制作啊

**Comment by faustliang** [comment]
> @faustliang 源码部署，数据库用mysql。

什么意思啊大佬，纯小白不懂。。。

**Comment by changyexing** [comment]
https://telegra.ph/Telegram-Bot-%E7%94%B5%E6%8A%A5%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%90%88%E9%9B%86-02-28

**Comment by faustliang** [comment]
> https://telegra.ph/Telegram-Bot-%E7%94%B5%E6%8A%A5%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%90%88%E9%9B%86-02-28

谢谢大佬

**Comment by jinzaizhichi** [comment]
@faustliang 部署好了吗？

**Comment by faustliang** [comment]
没有，我用的别人分享的BOT> @faustliang 部署好了吗？

**Comment by faustliang** [comment]
> @faustliang 部署好了吗？

没有啊，我用的其他大佬分享的BOT😆

**Comment by faustliang** [comment]
> @faustliang 部署好了吗？

![image](https://user-images.githubusercontent.com/63723974/111396812-d47f7180-86fa-11eb-97cc-b2ae985acce1.png)
c此外，纯小白，看不懂这个怎么解压运行啊，我用的Windows笔记本下载的

**Comment by changyexing** [comment]
这玩意儿不是部署在服务器上的吗......你小白就找点现成的机器人用吧🤣🤣

**Comment by faustliang** [comment]
> 这玩意儿不是部署在服务器上的吗......你小白就找点现成的机器人用吧🤣🤣

🤣🤣有可能的话，想自己做一下
我看了下，是需要Linux虚拟器上输入程序嘛
或者是gcp上搭建？🤣😆但是那个免费额度的，好像得绑定银行卡，国内的合适吗，怕泄露隐私

**Comment by changyexing** [comment]
这个得要服务器啊...你在自己笔记本上运行不是画蛇添足....买服务器去吧👀

**Comment by faustliang** [comment]
> 这个得要服务器啊...你在自己笔记本上运行不是画蛇添足....买服务器去吧👀

合适的服务器求推荐🧐

**Comment by changyexing** [comment]
我这种白嫖党当然只会白嫖啊🤣没有服务器，白嫖人家建好的bot

**Comment by changyexing** [comment]
阿里的学生机一年一二百，运行这种rss没啥问题

**Comment by faustliang** [comment]
> 我这种白嫖党当然只会白嫖啊🤣没有服务器，白嫖人家建好的bot

😝😝白嫖快乐，但有时可以试着玩一下

**Comment by faustliang** [comment]
> 阿里的学生机一年一二百，运行这种rss没啥问题

好的，我去看看

**Comment by indes** [comment]
链接后面单独的问号是无意义的，这里的订阅失败不是这个问题，换个rsshub实例试试，官方实例不稳定。例如这个：https://rsshub.rssforever.com/picuki/profile/dawning_crow/6
