### ISSUE TITLE
http: request canceled (Client.Timeout exceeded while awaiting headers) Go请求超时

### ISSUE THREAD

**Issue by zhnq** [indes/flowerss-bot#94]
请问有配置项能自主选择调大时间吗
ERROR   model/source.go:158     unable to fetch update  {"error": "Get https://rsshub.app/zzz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)", "source": {"ID":24,"Link":"https://rsshub.app/zzz","Title":"紫竹张先生","ErrorCount":0,"Content":null,"CreatedAt":"2021-03-23T14:45:17.762624584Z","UpdatedAt":"2021-03-24T01:26:22.413154639Z"}}
github.com/indes/flowerss-bot/model.(*Source).GetNewContents
        /flowerss/model/source.go:158
github.com/indes/flowerss-bot/task.Update
        /flowerss/task/update.go:21

**Comment by indes** [comment]
暂时没有这个配置项，建议更换rsshub实例使用，官方实例不稳定
