### ISSUE TITLE
无法启动，但我的sqlite3应该没问题啊。。。

### ISSUE THREAD

**Issue by qsdaqsdafqr** [indes/flowerss-bot#97]
![image](https://user-images.githubusercontent.com/40647452/112755287-921b3600-9012-11eb-866c-240935459555.png)

**Comment by indes** [comment]
自己编译的版本？SQLite依赖cgo

**Comment by qsdaqsdafqr** [comment]
> 自己编译的版本？SQLite依赖cgo

没有啊，直接下载解压的

**Comment by indes** [comment]
需要自己下载源码编译，或者使用docker版本
